version: "3.4"

services:
  server:
    image: nginx:1.17-alpine
    ports:
      - 8088:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app
    depends_on:
      - php-fpm
    networks:
      - backend

  php-fpm:
    build:
      dockerfile: ${PWD}/docker/php/Dockerfile
    restart: on-failure
    environment:
      - "ENV_SUBSTITUTION_ENABLE=true"
      - "PHP_MEMORY_LIMIT=512M"
      - "PHP_FPM_LISTEN=9090"
      - "PHP_SESSION_GC_MAXLIFETIME=7200"
    env_file:
      - .env
    expose:
      - "9090"
    volumes:
      - ./app:/app
      - ./.env:/app/.env
    working_dir: /app
    networks:
      - backend

  mariadb:
    image: mariadb:11.1
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD:-!ChangeMeRoot!}
      MYSQL_DATABASE: ${DATABASE_NAME:-app}
      MYSQL_USER: ${DATABASE_USER:-app}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD:-!ChangeMeRoot!}
    networks:
      - backend
    restart: on-failure
    volumes:
      - ./data/mariadb:/var/lib/mysql
      - ./data/log/mariadb:/var/log/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"

  memcached:
    image: memcached:1.5.3-alpine
    networks:
      - backend
    restart: on-failure

networks:
  backend:
